version: "3.9"

services:
  smc-python:
    build:
      context: ./trending-smc
      dockerfile: Dockerfile
    container_name: trending-smc
    ports:
      - "50051:50051"
    restart: unless-stopped

  go-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "9000:9000"
    environment:
      GIN_MODE: release
    depends_on:
      - smc-python
    restart: unless-stopped
